version: '{build}'
os: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- ps: .\build.ps1 -Target "CI" -Verbosity "Normal" -Configuration "Release"
test: off
deploy:
- provider: Environment
  name: MyGet (ES Snapback)
  on:
    branch: /release\/.+/